import type { UiCopy } from "../types";

const zhTw: UiCopy = {
  addCustomPrompt: "新增句子",
  appEyebrow: "SAYNEXT",
  appTitle: "AI 下一句",
  cancel: "取消",
  categoryCustom: "我的句子",
  categoryFavorites: "我的最愛",
  categoryRecent: "最近",
  categoryRecentEmpty: "最近使用",
  close: "關閉",
  confirm: "確認",
  delete: "刪除",
  deleteCustomPrompt: "刪除自訂句子",
  deleteCustomPromptBody: (title) =>
    `這會從本機移除「${title}」，也會從最近使用與收藏移除。`,
  editCustomPrompt: "編輯句子",
  customPromptBadge: "自訂",
  emptyCategoryCopy: "可以先切到其他情境，或新增自己的常用句子。",
  emptyCategoryTitle: "這個情境目前沒有句子。",
  emptyCustomCopy: "按右上角「新增句子」，建立自己的常用提示。",
  emptyCustomTitle: "還沒有自訂句子。",
  emptyFavoritesCopy: "點句子旁邊的愛心後，它會出現在這裡。",
  emptyFavoritesTitle: "還沒有我的最愛。",
  emptyRecentCopy: "複製幾句後，最近使用會出現在這裡。",
  emptyRecentTitle: "還沒有最近使用。",
  favorite: "收藏",
  footerCategory: "←→ 分類",
  footerCopy: "Enter 複製",
  footerFavorite: "F 最愛",
  footerJump: "Home/End 跳轉",
  footerSelect: "↑↓ 選取",
  labelContent: "句子內容",
  labelPlacement: "出現位置",
  labelTags: "標籤",
  labelTitle: "標題",
  language: "語言",
  myPromptsEyebrow: "My Prompts",
  newCustomPrompt: "新增句子",
  onboardingDismiss: "知道了",
  onboardingStepCopy: "點一句就會複製到剪貼簿。",
  onboardingStepHotkey: (shortcutLabel) => `按 ${shortcutLabel} 叫出 SayNext。`,
  onboardingStepPaste: "貼到 ChatGPT、Claude 或 Codex 繼續對話。",
  onboardingTitle: "第一次使用，只要三步",
  noticeAdded: (title) => `已新增：${title}`,
  noticeCopied: (title) => `已複製：${title}`,
  noticeCopyFailed: "複製失敗，請再試一次。",
  noticeDeleted: (title) => `已刪除：${title}`,
  noticeFavoriteAdded: (title) => `已加入最愛：${title}`,
  noticeFavoriteRemoved: (title) => `已移出最愛：${title}`,
  noticeUpdated: (title) => `已更新：${title}`,
  noticeImported: (count) => `已匯入 ${count} 個自訂句子`,
  noticeImportFailed: "匯入失敗，請確認檔案格式。",
  noticeExported: (count) => `已匯出 ${count} 個自訂句子`,
  placeholderContent: "請先把這件事拆成 3 到 5 個步驟，並告訴我第一步要做什麼。",
  placeholderTags: "planning, codex, writing",
  placeholderTitle: "例如：請先拆任務",
  save: "儲存",
  settings: "開啟偏好設定",
  settingsEyebrow: "設定",
  settingsAutostartChecking: "正在檢查目前狀態。",
  settingsAutostartDescription: "登入系統後自動常駐在 menu bar / tray。",
  settingsAutostartTitle: "開機自動啟動",
  settingsAutostartUnavailable: "Web preview 不支援，桌面版可使用。",
  settingsClose: "關閉偏好設定",
  settingsGithubDescription: "查看原始碼、下載版本與回報問題。",
  settingsGithubTitle: "GitHub repository",
  settingsImportButton: "匯入",
  settingsExportButton: "匯出",
  settingsPromptDataDescription: "備份、換電腦，或分享你的自訂句子 JSON。",
  settingsPromptDataTitle: "我的句子資料",
  settingsNote:
    "SayNext 是開源、離線優先的小工具，專為不知道下一句該怎麼問 AI 的人設計。",
  settingsShortcutDescription: (platformName) =>
    `目前平台：${platformName}。操作邏輯與另一個桌面系統保持一致。`,
  settingsShortcutTitle: "快捷鍵",
  settingsThemeDark: "深色",
  settingsThemeDescription: "選擇 SayNext 使用淺色、深色，或跟隨系統外觀。",
  settingsThemeLight: "淺色",
  settingsThemeSystem: "跟隨系統",
  settingsThemeTitle: "外觀",
  settingsTitle: "偏好設定",
  settingsUpdateAvailable: (version, currentVersion) =>
    `找到 ${version}，目前版本是 ${currentVersion}。`,
  settingsUpdateButtonCheck: "檢查",
  settingsUpdateButtonInstall: "更新",
  settingsUpdateChecking: "正在檢查 GitHub 上是否有新版本。",
  settingsUpdateCheckFailed: "目前無法檢查更新。請確認網路連線，或稍後再試。",
  settingsUpdateDescription: "從 GitHub Release 檢查新版並自動安裝。",
  settingsUpdateDownloading: "正在下載並安裝更新。",
  settingsUpdateDownloadingPercent: (percent) => `正在下載並安裝更新：${percent}%。`,
  settingsUpdateError: "更新檢查失敗，請稍後再試。",
  settingsUpdateInstallFailed: "更新安裝失敗。請重新檢查更新，或到 GitHub 下載最新版本。",
  settingsUpdateNotAvailable: "目前已經是最新版本。",
  settingsUpdateRestarting: "更新完成，正在重新啟動 SayNext。",
  settingsUpdateTitle: "軟體更新",
  settingsWindowResetDescription: "把 SayNext 移回螢幕中央。",
  settingsWindowResetTitle: "重設視窗位置",
  unfavorite: "取消收藏"
};

const en: UiCopy = {
  addCustomPrompt: "Add prompt",
  appEyebrow: "SAYNEXT",
  appTitle: "AI Next Prompt",
  cancel: "Cancel",
  categoryCustom: "My prompts",
  categoryFavorites: "Favorites",
  categoryRecent: "Recent",
  categoryRecentEmpty: "Recently used",
  close: "Close",
  confirm: "Confirm",
  delete: "Delete",
  deleteCustomPrompt: "Delete custom prompt",
  deleteCustomPromptBody: (title) =>
    `This removes "${title}" from this device, recent prompts, and favorites.`,
  editCustomPrompt: "Edit prompt",
  customPromptBadge: "Custom",
  emptyCategoryCopy: "Switch to another context or add your own reusable prompt.",
  emptyCategoryTitle: "No prompts in this context yet.",
  emptyCustomCopy: "Use Add prompt to create your own reusable prompt.",
  emptyCustomTitle: "No custom prompts yet.",
  emptyFavoritesCopy: "Mark prompts with the heart icon to collect them here.",
  emptyFavoritesTitle: "No favorites yet.",
  emptyRecentCopy: "Copied prompts will show up here.",
  emptyRecentTitle: "No recent prompts yet.",
  favorite: "Favorite",
  footerCategory: "←→ Categories",
  footerCopy: "Enter Copy",
  footerFavorite: "F Favorite",
  footerJump: "Home/End Jump",
  footerSelect: "↑↓ Select",
  labelContent: "Prompt text",
  labelPlacement: "Where it appears",
  labelTags: "Tags",
  labelTitle: "Title",
  language: "Language",
  myPromptsEyebrow: "My Prompts",
  newCustomPrompt: "Add prompt",
  onboardingDismiss: "Got it",
  onboardingStepCopy: "Click a prompt to copy it.",
  onboardingStepHotkey: (shortcutLabel) => `Press ${shortcutLabel} to open SayNext.`,
  onboardingStepPaste: "Paste into ChatGPT, Claude, or Codex.",
  onboardingTitle: "First time here? Three steps",
  noticeAdded: (title) => `Added: ${title}`,
  noticeCopied: (title) => `Copied: ${title}`,
  noticeCopyFailed: "Copy failed. Please try again.",
  noticeDeleted: (title) => `Deleted: ${title}`,
  noticeFavoriteAdded: (title) => `Added to favorites: ${title}`,
  noticeFavoriteRemoved: (title) => `Removed from favorites: ${title}`,
  noticeUpdated: (title) => `Updated: ${title}`,
  noticeImported: (count) => `Imported ${count} custom prompts`,
  noticeImportFailed: "Import failed. Check the file format.",
  noticeExported: (count) => `Exported ${count} custom prompts`,
  placeholderContent: "Break this into 3 to 5 steps and tell me what to do first.",
  placeholderTags: "planning, codex, writing",
  placeholderTitle: "Example: Break this down",
  save: "Save",
  settings: "Open settings",
  settingsEyebrow: "Settings",
  settingsAutostartChecking: "Checking the current status.",
  settingsAutostartDescription: "Keep SayNext available from the menu bar / tray after login.",
  settingsAutostartTitle: "Launch at login",
  settingsAutostartUnavailable: "Not available in web preview. Use the desktop app.",
  settingsClose: "Close settings",
  settingsGithubDescription: "View source, download releases, and report issues.",
  settingsGithubTitle: "GitHub repository",
  settingsImportButton: "Import",
  settingsExportButton: "Export",
  settingsPromptDataDescription: "Back up, move devices, or share your custom prompt JSON.",
  settingsPromptDataTitle: "My prompt data",
  settingsNote:
    "SayNext is open-source, offline-first, and built for people who do not know what to ask AI next.",
  settingsShortcutDescription: (platformName) =>
    `Current platform: ${platformName}. The interaction model stays consistent across desktop systems.`,
  settingsShortcutTitle: "Shortcut",
  settingsThemeDark: "Dark",
  settingsThemeDescription: "Choose a light theme, dark theme, or follow the system appearance.",
  settingsThemeLight: "Light",
  settingsThemeSystem: "System",
  settingsThemeTitle: "Appearance",
  settingsTitle: "Settings",
  settingsUpdateAvailable: (version, currentVersion) =>
    `Version ${version} is available. Current version: ${currentVersion}.`,
  settingsUpdateButtonCheck: "Check",
  settingsUpdateButtonInstall: "Update",
  settingsUpdateChecking: "Checking GitHub Releases for a new version.",
  settingsUpdateCheckFailed: "Could not check for updates. Check your connection and try again.",
  settingsUpdateDescription: "Check GitHub Releases and install updates automatically.",
  settingsUpdateDownloading: "Downloading and installing the update.",
  settingsUpdateDownloadingPercent: (percent) => `Downloading and installing: ${percent}%.`,
  settingsUpdateError: "Update check failed. Please try again later.",
  settingsUpdateInstallFailed:
    "Update installation failed. Check for updates again or download the latest release from GitHub.",
  settingsUpdateNotAvailable: "You are already on the latest version.",
  settingsUpdateRestarting: "Update complete. Restarting SayNext.",
  settingsUpdateTitle: "Software update",
  settingsWindowResetDescription: "Move SayNext back to the center of the screen.",
  settingsWindowResetTitle: "Reset window position",
  unfavorite: "Remove favorite"
};

export function getUiCopy(locale: string): UiCopy {
  return locale === "en" ? en : zhTw;
}
