import type { UiCopy } from "../types";

const zhTw: UiCopy = {
  addCustomPrompt: "新增句子",
  appEyebrow: "SAYNEXT",
  appTitle: "AI 下一句",
  cancel: "取消",
  categoryCustom: "我的句子",
  categoryFavorites: "我的最愛",
  categoryRecent: "最近",
  categoryRecentEmpty: "最近使用",
  tabConfused: "看不懂",
  tabConfusedHint: "先把問題說清楚，避免回覆太快失焦。",
  tabExecute: "做下去",
  tabExecuteHint: "把計畫變成下一步可執行的內容。",
  tabImprove: "改進回答",
  tabImproveHint: "請 AI 重思考、重回到更好版本。",
  tabResearchPlanning: "研究規劃",
  tabResearchPlanningHint: "先蒐資料、比對觀點，再排定做法。",
  tabReview: "檢查",
  tabReviewHint: "確認問題、風險與品質缺口。",
  tabStart: "開始",
  tabStartHint: "先定位需求，讓第一句更精準。",
  close: "關閉",
  confirm: "確認",
  delete: "刪除",
  deleteCustomPrompt: "刪除自訂句子",
  deleteCustomPromptBody: (title) =>
    `這會從本機移除「${title}」，也會從最近使用與收藏移除。`,
  editCustomPrompt: "編輯句子",
  customPromptBadge: "自訂",
  emptyCategoryCopy: "可以先切到其他情境，或新增自己的常用句子。",
  emptyCategoryTitle: "這個情境目前沒有句子。",
  emptyCustomCopy: "按右上角「新增句子」，建立自己的常用提示。",
  emptyCustomTitle: "還沒有自訂句子。",
  emptyFavoritesCopy: "點句子旁邊的愛心後，它會出現在這裡。",
  emptyFavoritesTitle: "還沒有我的最愛。",
  emptyRecentCopy: "複製幾句後，最近使用會出現在這裡。",
  emptyRecentTitle: "還沒有最近使用。",
  favorite: "收藏",
  footerCategory: "←→ 分類",
  footerCopy: "Enter 複製",
  footerFavorite: "F 最愛",
  footerJump: "Home/End 跳轉",
  footerSelect: "↑↓ 選取",
  labelContent: "句子內容",
  labelPlacement: "出現位置",
  labelTags: "標籤",
  labelTitle: "標題",
  language: "語言",
  myPromptsEyebrow: "My Prompts",
  newCustomPrompt: "新增句子",
  onboardingDismiss: "知道了",
  onboardingStepCopy: "點一句就會複製到剪貼簿。",
  onboardingStepHotkey: (shortcutLabel) => `按 ${shortcutLabel} 叫出 SayNext。`,
  onboardingStepPaste: "貼到 ChatGPT、Claude 或 Codex 繼續對話。",
  onboardingTitle: "第一次使用，只要三步",
  noticeAdded: (title) => `已新增：${title}`,
  noticeCopied: (title) => `已複製：${title}`,
  noticeCopyFailed: "複製失敗，請再試一次。",
  noticeDeleted: (title) => `已刪除：${title}`,
  noticeFavoriteAdded: (title) => `已加入最愛：${title}`,
  noticeFavoriteRemoved: (title) => `已移出最愛：${title}`,
  noticeUpdated: (title) => `已更新：${title}`,
  noticeImported: (count) => `已匯入 ${count} 個自訂句子`,
  noticeImportFailed: "匯入失敗，請確認檔案格式。",
  noticeExported: (count) => `已匯出 ${count} 個自訂句子`,
  placeholderContent: "請先把這件事拆成 3 到 5 個步驟，並告訴我第一步要做什麼。",
  placeholderTags: "planning, codex, writing",
  placeholderTitle: "例如：請先拆任務",
  save: "儲存",
  settings: "開啟偏好設定",
  settingsEyebrow: "設定",
  settingsAutostartChecking: "正在檢查目前狀態。",
  settingsAutostartDescription: "登入系統後自動常駐在 menu bar / tray。",
  settingsAutostartTitle: "開機自動啟動",
  settingsAutostartUnavailable: "Web preview 不支援，桌面版可使用。",
  settingsClose: "關閉偏好設定",
  settingsGithubDescription: "查看原始碼、下載版本與回報問題。",
  settingsGithubTitle: "GitHub repository",
  settingsImportButton: "匯入",
  settingsExportButton: "匯出",
  settingsPromptDataDescription: "備份、換電腦，或分享你的自訂句子 JSON。",
  settingsPromptDataTitle: "我的句子資料",
  settingsNote:
    "SayNext 是開源、離線優先的小工具，專為不知道下一句該怎麼問 AI 的人設計。",
  settingsShortcutDescription: (platformName) =>
    `目前平台：${platformName}。操作邏輯與另一個桌面系統保持一致。`,
  settingsShortcutTitle: "快捷鍵",
  settingsThemeDark: "深色",
  settingsThemeDescription: "選擇 SayNext 使用淺色、深色，或跟隨系統外觀。",
  settingsThemeLight: "淺色",
  settingsThemeSystem: "跟隨系統",
  settingsThemeTitle: "外觀",
  settingsTitle: "偏好設定",
  settingsUpdateAvailable: (version, currentVersion) =>
    `找到 ${version}，目前版本是 ${currentVersion}。`,
  settingsUpdateButtonCheck: "檢查",
  settingsUpdateButtonInstall: "更新",
  settingsUpdateChecking: "正在檢查 GitHub 上是否有新版本。",
  settingsUpdateCheckFailed: "目前無法檢查更新。請確認網路連線，或稍後再試。",
  settingsUpdateDescription: "從 GitHub Release 檢查新版並自動安裝。",
  settingsUpdateDownloading: "正在下載並安裝更新。",
  settingsUpdateDownloadingPercent: (percent) => `正在下載並安裝更新：${percent}%。`,
  settingsUpdateError: "更新檢查失敗，請稍後再試。",
  settingsUpdateInstallFailed: "更新安裝失敗。請重新檢查更新，或到 GitHub 下載最新版本。",
  settingsUpdateNotAvailable: "目前已經是最新版本。",
  settingsUpdateRestarting: "更新完成，正在重新啟動 SayNext。",
  settingsUpdateTitle: "軟體更新",
  settingsWindowResetDescription: "把 SayNext 移回螢幕中央。",
  settingsWindowResetTitle: "重設視窗位置",
  unfavorite: "取消收藏"
};

const en: UiCopy = {
  addCustomPrompt: "Add prompt",
  appEyebrow: "SAYNEXT",
  appTitle: "AI Next Prompt",
  cancel: "Cancel",
  categoryCustom: "My prompts",
  categoryFavorites: "Favorites",
  categoryRecent: "Recent",
  categoryRecentEmpty: "Recently used",
  tabConfused: "Confused",
  tabConfusedHint: "Clarify what is unclear before continuing.",
  tabExecute: "Execute",
  tabExecuteHint: "Move from plan to concrete next actions.",
  tabImprove: "Improve",
  tabImproveHint: "Ask for a better, more practical version.",
  tabResearchPlanning: "Research & Plan",
  tabResearchPlanningHint: "Collect references and shape a practical roadmap.",
  tabReview: "Review",
  tabReviewHint: "Check quality, gaps, and risks before finalizing.",
  tabStart: "Start",
  tabStartHint: "Align goals and prepare your first prompt.",
  close: "Close",
  confirm: "Confirm",
  delete: "Delete",
  deleteCustomPrompt: "Delete custom prompt",
  deleteCustomPromptBody: (title) =>
    `This removes "${title}" from this device, recent prompts, and favorites.`,
  editCustomPrompt: "Edit prompt",
  customPromptBadge: "Custom",
  emptyCategoryCopy: "Switch to another context or add your own reusable prompt.",
  emptyCategoryTitle: "No prompts in this context yet.",
  emptyCustomCopy: "Use Add prompt to create your own reusable prompt.",
  emptyCustomTitle: "No custom prompts yet.",
  emptyFavoritesCopy: "Mark prompts with the heart icon to collect them here.",
  emptyFavoritesTitle: "No favorites yet.",
  emptyRecentCopy: "Copied prompts will show up here.",
  emptyRecentTitle: "No recent prompts yet.",
  favorite: "Favorite",
  footerCategory: "←→ Categories",
  footerCopy: "Enter Copy",
  footerFavorite: "F Favorite",
  footerJump: "Home/End Jump",
  footerSelect: "↑↓ Select",
  labelContent: "Prompt text",
  labelPlacement: "Where it appears",
  labelTags: "Tags",
  labelTitle: "Title",
  language: "Language",
  myPromptsEyebrow: "My Prompts",
  newCustomPrompt: "Add prompt",
  onboardingDismiss: "Got it",
  onboardingStepCopy: "Click a prompt to copy it.",
  onboardingStepHotkey: (shortcutLabel) => `Press ${shortcutLabel} to open SayNext.`,
  onboardingStepPaste: "Paste into ChatGPT, Claude, or Codex.",
  onboardingTitle: "First time here? Three steps",
  noticeAdded: (title) => `Added: ${title}`,
  noticeCopied: (title) => `Copied: ${title}`,
  noticeCopyFailed: "Copy failed. Please try again.",
  noticeDeleted: (title) => `Deleted: ${title}`,
  noticeFavoriteAdded: (title) => `Added to favorites: ${title}`,
  noticeFavoriteRemoved: (title) => `Removed from favorites: ${title}`,
  noticeUpdated: (title) => `Updated: ${title}`,
  noticeImported: (count) => `Imported ${count} custom prompts`,
  noticeImportFailed: "Import failed. Check the file format.",
  noticeExported: (count) => `Exported ${count} custom prompts`,
  placeholderContent: "Break this into 3 to 5 steps and tell me what to do first.",
  placeholderTags: "planning, codex, writing",
  placeholderTitle: "Example: Break this down",
  save: "Save",
  settings: "Open settings",
  settingsEyebrow: "Settings",
  settingsAutostartChecking: "Checking the current status.",
  settingsAutostartDescription: "Keep SayNext available from the menu bar / tray after login.",
  settingsAutostartTitle: "Launch at login",
  settingsAutostartUnavailable: "Not available in web preview. Use the desktop app.",
  settingsClose: "Close settings",
  settingsGithubDescription: "View source, download releases, and report issues.",
  settingsGithubTitle: "GitHub repository",
  settingsImportButton: "Import",
  settingsExportButton: "Export",
  settingsPromptDataDescription: "Back up, move devices, or share your custom prompt JSON.",
  settingsPromptDataTitle: "My prompt data",
  settingsNote:
    "SayNext is open-source, offline-first, and built for people who do not know what to ask AI next.",
  settingsShortcutDescription: (platformName) =>
    `Current platform: ${platformName}. The interaction model stays consistent across desktop systems.`,
  settingsShortcutTitle: "Shortcut",
  settingsThemeDark: "Dark",
  settingsThemeDescription: "Choose a light theme, dark theme, or follow the system appearance.",
  settingsThemeLight: "Light",
  settingsThemeSystem: "System",
  settingsThemeTitle: "Appearance",
  settingsTitle: "Settings",
  settingsUpdateAvailable: (version, currentVersion) =>
    `Version ${version} is available. Current version: ${currentVersion}.`,
  settingsUpdateButtonCheck: "Check",
  settingsUpdateButtonInstall: "Update",
  settingsUpdateChecking: "Checking GitHub Releases for a new version.",
  settingsUpdateCheckFailed: "Could not check for updates. Check your connection and try again.",
  settingsUpdateDescription: "Check GitHub Releases and install updates automatically.",
  settingsUpdateDownloading: "Downloading and installing the update.",
  settingsUpdateDownloadingPercent: (percent) => `Downloading and installing: ${percent}%.`,
  settingsUpdateError: "Update check failed. Please try again later.",
  settingsUpdateInstallFailed:
    "Update installation failed. Check for updates again or download the latest release from GitHub.",
  settingsUpdateNotAvailable: "You are already on the latest version.",
  settingsUpdateRestarting: "Update complete. Restarting SayNext.",
  settingsUpdateTitle: "Software update",
  settingsWindowResetDescription: "Move SayNext back to the center of the screen.",
  settingsWindowResetTitle: "Reset window position",
  unfavorite: "Remove favorite"
};

const ja: UiCopy = {
  ...en,
  addCustomPrompt: "プロンプト追加",
  appTitle: "AI 次の一言",
  cancel: "キャンセル",
  categoryCustom: "自分の文",
  categoryFavorites: "お気に入り",
  categoryRecent: "最近",
  categoryRecentEmpty: "最近使用",
  tabConfused: "わからない",
  tabConfusedHint: "まず不明点をはっきりさせてから進めます。",
  tabExecute: "実行",
  tabExecuteHint: "計画を具体的な次の一歩に変換します。",
  tabImprove: "改善",
  tabImproveHint: "より実用的でわかりやすい表現を求めます。",
  tabResearchPlanning: "調査と計画",
  tabResearchPlanningHint: "資料を集め、比較し、実行方針を決めます。",
  tabReview: "チェック",
  tabReviewHint: "問題点・リスク・品質不足を確認します。",
  tabStart: "開始",
  tabStartHint: "まず目的を整理して、最初の一文を決めます。",
  close: "閉じる",
  confirm: "確認",
  delete: "削除",
  editCustomPrompt: "文を編集",
  customPromptBadge: "自作",
  favorite: "お気に入り",
  footerCategory: "←→ 分類",
  footerCopy: "Enter コピー",
  footerFavorite: "F お気に入り",
  footerJump: "Home/End 移動",
  footerSelect: "↑↓ 選択",
  labelContent: "本文",
  labelPlacement: "表示場所",
  labelTags: "タグ",
  labelTitle: "タイトル",
  language: "言語",
  newCustomPrompt: "プロンプト追加",
  onboardingDismiss: "わかりました",
  onboardingStepCopy: "文をクリックするとコピーされます。",
  onboardingStepHotkey: (shortcutLabel) => `${shortcutLabel} で SayNext を開きます。`,
  onboardingStepPaste: "ChatGPT、Claude、Codex に貼り付けます。",
  onboardingTitle: "初めての方へ：3ステップ",
  noticeCopied: (title) => `コピーしました：${title}`,
  noticeCopyFailed: "コピーできませんでした。もう一度お試しください。",
  placeholderContent: "これを3〜5ステップに分け、最初に何をすべきか教えてください。",
  placeholderTitle: "例：タスクを分解して",
  save: "保存",
  settings: "設定を開く",
  settingsEyebrow: "設定",
  settingsClose: "設定を閉じる",
  settingsImportButton: "インポート",
  settingsExportButton: "エクスポート",
  settingsPromptDataTitle: "自分の文データ",
  settingsTitle: "設定",
  settingsUpdateButtonCheck: "確認",
  settingsUpdateButtonInstall: "更新",
  settingsUpdateNotAvailable: "すでに最新バージョンです。",
  settingsUpdateTitle: "ソフトウェア更新",
  unfavorite: "お気に入り解除"
};

const ko: UiCopy = {
  ...en,
  addCustomPrompt: "문장 추가",
  appTitle: "AI 다음 문장",
  cancel: "취소",
  categoryCustom: "내 문장",
  categoryFavorites: "즐겨찾기",
  categoryRecent: "최근",
  categoryRecentEmpty: "최근 사용",
  tabConfused: "이해가 안 돼",
  tabConfusedHint: "애매한 부분을 먼저 분명히 한 뒤 진행해요.",
  tabExecute: "실행",
  tabExecuteHint: "계획을 바로 실행할 수 있는 다음 단계로 바꿉니다.",
  tabImprove: "개선",
  tabImproveHint: "더 실용적이고 좋은 결과로 다듬어 달라고 요청하세요.",
  tabResearchPlanning: "연구와 계획",
  tabResearchPlanningHint: "자료를 모으고 비교한 뒤 실제 계획으로 정리해요.",
  tabReview: "검토",
  tabReviewHint: "문제, 리스크, 품질 누락을 먼저 확인해요.",
  tabStart: "시작",
  tabStartHint: "우선 목표를 정리해 첫 문장을 잡아요.",
  close: "닫기",
  confirm: "확인",
  delete: "삭제",
  editCustomPrompt: "문장 편집",
  customPromptBadge: "사용자",
  favorite: "즐겨찾기",
  footerCategory: "←→ 분류",
  footerCopy: "Enter 복사",
  footerFavorite: "F 즐겨찾기",
  footerJump: "Home/End 이동",
  footerSelect: "↑↓ 선택",
  labelContent: "문장 내용",
  labelPlacement: "표시 위치",
  labelTags: "태그",
  labelTitle: "제목",
  language: "언어",
  newCustomPrompt: "문장 추가",
  onboardingDismiss: "알겠습니다",
  onboardingStepCopy: "문장을 클릭하면 복사됩니다.",
  onboardingStepHotkey: (shortcutLabel) => `${shortcutLabel}를 눌러 SayNext를 여세요.`,
  onboardingStepPaste: "ChatGPT, Claude, Codex에 붙여넣으세요.",
  onboardingTitle: "처음이라면 세 단계만 기억하세요",
  noticeCopied: (title) => `복사됨: ${title}`,
  noticeCopyFailed: "복사에 실패했습니다. 다시 시도해 주세요.",
  placeholderContent: "이 일을 3~5단계로 나누고 첫 단계에서 무엇을 해야 하는지 알려 주세요.",
  placeholderTitle: "예: 작업을 나눠 주세요",
  save: "저장",
  settings: "설정 열기",
  settingsEyebrow: "설정",
  settingsClose: "설정 닫기",
  settingsImportButton: "가져오기",
  settingsExportButton: "내보내기",
  settingsPromptDataTitle: "내 문장 데이터",
  settingsTitle: "설정",
  settingsUpdateButtonCheck: "확인",
  settingsUpdateButtonInstall: "업데이트",
  settingsUpdateNotAvailable: "이미 최신 버전입니다.",
  settingsUpdateTitle: "소프트웨어 업데이트",
  unfavorite: "즐겨찾기 해제"
};

const es: UiCopy = {
  ...en,
  addCustomPrompt: "Añadir prompt",
  appTitle: "Siguiente prompt de IA",
  cancel: "Cancelar",
  categoryCustom: "Mis prompts",
  categoryFavorites: "Favoritos",
  categoryRecent: "Recientes",
  categoryRecentEmpty: "Usados recientemente",
  tabConfused: "No entiendo",
  tabConfusedHint: "Aclara qué no entendiste antes de seguir.",
  tabExecute: "Hacer",
  tabExecuteHint: "Convierte el plan en siguientes acciones concretas.",
  tabImprove: "Mejorar",
  tabImproveHint: "Pide una versión más práctica y útil.",
  tabResearchPlanning: "Investigar y planificar",
  tabResearchPlanningHint: "Recoge referencias y construye un plan práctico.",
  tabReview: "Revisar",
  tabReviewHint: "Revisa riesgos, huecos y calidad antes de cerrar.",
  tabStart: "Comenzar",
  tabStartHint: "Define objetivo y prepara tu primera pregunta.",
  close: "Cerrar",
  confirm: "Confirmar",
  delete: "Eliminar",
  editCustomPrompt: "Editar prompt",
  customPromptBadge: "Personalizado",
  favorite: "Favorito",
  labelContent: "Texto del prompt",
  labelPlacement: "Dónde aparece",
  labelTags: "Etiquetas",
  labelTitle: "Título",
  language: "Idioma",
  newCustomPrompt: "Añadir prompt",
  onboardingDismiss: "Entendido",
  onboardingStepCopy: "Haz clic en un prompt para copiarlo.",
  onboardingStepHotkey: (shortcutLabel) => `Pulsa ${shortcutLabel} para abrir SayNext.`,
  onboardingStepPaste: "Pégalo en ChatGPT, Claude o Codex.",
  onboardingTitle: "¿Primera vez? Tres pasos",
  noticeCopied: (title) => `Copiado: ${title}`,
  noticeCopyFailed: "No se pudo copiar. Inténtalo de nuevo.",
  save: "Guardar",
  settings: "Abrir ajustes",
  settingsEyebrow: "Ajustes",
  settingsClose: "Cerrar ajustes",
  settingsImportButton: "Importar",
  settingsExportButton: "Exportar",
  settingsTitle: "Ajustes",
  settingsUpdateButtonCheck: "Buscar",
  settingsUpdateButtonInstall: "Actualizar",
  settingsUpdateNotAvailable: "Ya tienes la versión más reciente.",
  settingsUpdateTitle: "Actualización de software",
  unfavorite: "Quitar favorito"
};

const fr: UiCopy = {
  ...en,
  addCustomPrompt: "Ajouter un prompt",
  appTitle: "Prochain prompt IA",
  cancel: "Annuler",
  categoryCustom: "Mes prompts",
  categoryFavorites: "Favoris",
  categoryRecent: "Récents",
  categoryRecentEmpty: "Utilisés récemment",
  tabConfused: "Confus",
  tabConfusedHint: "Clarifie ce qui n’est pas clair avant d’avancer.",
  tabExecute: "Exécuter",
  tabExecuteHint: "Transforme le plan en prochaines actions concrètes.",
  tabImprove: "Améliorer",
  tabImproveHint: "Demande une version plus utile et plus claire.",
  tabResearchPlanning: "Rechercher & planifier",
  tabResearchPlanningHint: "Collecte des références puis compose une feuille de route.",
  tabReview: "Revoir",
  tabReviewHint: "Vérifie les risques, les trous et la qualité.",
  tabStart: "Commencer",
  tabStartHint: "Clarifie l’objectif puis prépare ta première prompt.",
  close: "Fermer",
  confirm: "Confirmer",
  delete: "Supprimer",
  editCustomPrompt: "Modifier le prompt",
  customPromptBadge: "Perso",
  favorite: "Favori",
  labelContent: "Texte du prompt",
  labelPlacement: "Emplacement",
  labelTags: "Tags",
  labelTitle: "Titre",
  language: "Langue",
  newCustomPrompt: "Ajouter un prompt",
  onboardingDismiss: "Compris",
  onboardingStepCopy: "Cliquez sur un prompt pour le copier.",
  onboardingStepHotkey: (shortcutLabel) => `Appuyez sur ${shortcutLabel} pour ouvrir SayNext.`,
  onboardingStepPaste: "Collez dans ChatGPT, Claude ou Codex.",
  onboardingTitle: "Première utilisation ? Trois étapes",
  noticeCopied: (title) => `Copié : ${title}`,
  noticeCopyFailed: "La copie a échoué. Réessayez.",
  save: "Enregistrer",
  settings: "Ouvrir les réglages",
  settingsEyebrow: "Réglages",
  settingsClose: "Fermer les réglages",
  settingsImportButton: "Importer",
  settingsExportButton: "Exporter",
  settingsTitle: "Réglages",
  settingsUpdateButtonCheck: "Vérifier",
  settingsUpdateButtonInstall: "Mettre à jour",
  settingsUpdateNotAvailable: "Vous utilisez déjà la dernière version.",
  settingsUpdateTitle: "Mise à jour logicielle",
  unfavorite: "Retirer des favoris"
};

const de: UiCopy = {
  ...en,
  addCustomPrompt: "Prompt hinzufügen",
  appTitle: "Nächster KI-Prompt",
  cancel: "Abbrechen",
  categoryCustom: "Meine Prompts",
  categoryFavorites: "Favoriten",
  categoryRecent: "Zuletzt",
  categoryRecentEmpty: "Zuletzt verwendet",
  tabConfused: "Verwirrt",
  tabConfusedHint: "Klär zuerst, was unklar ist, bevor du weiter machst.",
  tabExecute: "Ausführen",
  tabExecuteHint: "Wandle den Plan in konkrete nächste Schritte um.",
  tabImprove: "Verbessern",
  tabImproveHint: "Bitte um eine praktischere und bessere Version.",
  tabResearchPlanning: "Forschen & planen",
  tabResearchPlanningHint: "Quellen sammeln und daraus eine praktische Roadmap ableiten.",
  tabReview: "Überprüfen",
  tabReviewHint: "Prüfe Risiken, Lücken und Qualität vor dem Abschluss.",
  tabStart: "Start",
  tabStartHint: "Ziel setzen und den ersten Prompt vorbereiten.",
  close: "Schließen",
  confirm: "Bestätigen",
  delete: "Löschen",
  editCustomPrompt: "Prompt bearbeiten",
  customPromptBadge: "Eigen",
  favorite: "Favorit",
  labelContent: "Prompt-Text",
  labelPlacement: "Anzeigeort",
  labelTags: "Tags",
  labelTitle: "Titel",
  language: "Sprache",
  newCustomPrompt: "Prompt hinzufügen",
  onboardingDismiss: "Verstanden",
  onboardingStepCopy: "Klicke auf einen Prompt, um ihn zu kopieren.",
  onboardingStepHotkey: (shortcutLabel) => `Drücke ${shortcutLabel}, um SayNext zu öffnen.`,
  onboardingStepPaste: "In ChatGPT, Claude oder Codex einfügen.",
  onboardingTitle: "Zum ersten Mal hier? Drei Schritte",
  noticeCopied: (title) => `Kopiert: ${title}`,
  noticeCopyFailed: "Kopieren fehlgeschlagen. Bitte erneut versuchen.",
  save: "Speichern",
  settings: "Einstellungen öffnen",
  settingsEyebrow: "Einstellungen",
  settingsClose: "Einstellungen schließen",
  settingsImportButton: "Importieren",
  settingsExportButton: "Exportieren",
  settingsTitle: "Einstellungen",
  settingsUpdateButtonCheck: "Prüfen",
  settingsUpdateButtonInstall: "Aktualisieren",
  settingsUpdateNotAvailable: "Du nutzt bereits die neueste Version.",
  settingsUpdateTitle: "Softwareupdate",
  unfavorite: "Favorit entfernen"
};

const ptBr: UiCopy = {
  ...en,
  addCustomPrompt: "Adicionar prompt",
  appTitle: "Próximo prompt de IA",
  cancel: "Cancelar",
  categoryCustom: "Meus prompts",
  categoryFavorites: "Favoritos",
  categoryRecent: "Recentes",
  categoryRecentEmpty: "Usados recentemente",
  tabConfused: "Não entendi",
  tabConfusedHint: "Primeiro, esclareça o que não ficou claro antes de continuar.",
  tabExecute: "Executar",
  tabExecuteHint: "Transforme o plano em próximos passos concretos.",
  tabImprove: "Melhorar",
  tabImproveHint: "Peça uma versão mais prática e melhor.",
  tabResearchPlanning: "Pesquisar e planejar",
  tabResearchPlanningHint: "Reúna referências e defina um roteiro prático.",
  tabReview: "Revisar",
  tabReviewHint: "Verifique riscos, lacunas e qualidade antes de finalizar.",
  tabStart: "Começar",
  tabStartHint: "Defina o objetivo e prepare seu primeiro prompt.",
  close: "Fechar",
  confirm: "Confirmar",
  delete: "Excluir",
  editCustomPrompt: "Editar prompt",
  customPromptBadge: "Personalizado",
  favorite: "Favorito",
  labelContent: "Texto do prompt",
  labelPlacement: "Onde aparece",
  labelTags: "Tags",
  labelTitle: "Título",
  language: "Idioma",
  newCustomPrompt: "Adicionar prompt",
  onboardingDismiss: "Entendi",
  onboardingStepCopy: "Clique em um prompt para copiar.",
  onboardingStepHotkey: (shortcutLabel) => `Pressione ${shortcutLabel} para abrir o SayNext.`,
  onboardingStepPaste: "Cole no ChatGPT, Claude ou Codex.",
  onboardingTitle: "Primeira vez? Três passos",
  noticeCopied: (title) => `Copiado: ${title}`,
  noticeCopyFailed: "Falha ao copiar. Tente novamente.",
  save: "Salvar",
  settings: "Abrir configurações",
  settingsEyebrow: "Configurações",
  settingsClose: "Fechar configurações",
  settingsImportButton: "Importar",
  settingsExportButton: "Exportar",
  settingsTitle: "Configurações",
  settingsUpdateButtonCheck: "Verificar",
  settingsUpdateButtonInstall: "Atualizar",
  settingsUpdateNotAvailable: "Você já está na versão mais recente.",
  settingsUpdateTitle: "Atualização de software",
  unfavorite: "Remover favorito"
};

export function getUiCopy(locale: string): UiCopy {
  const copies: Record<string, UiCopy> = {
    "zh-TW": zhTw,
    en,
    ja,
    ko,
    es,
    fr,
    de,
    "pt-BR": ptBr
  };

  return copies[locale] ?? en;
}
