import type { UiCopy } from "../types";

const zhTw: UiCopy = {
  addCustomPrompt: "新增句子",
  allCategories: "全部分類",
  cancel: "取消",
  categoryCustom: "我的句子",
  categoryRecent: "最近",
  close: "關閉",
  confirm: "確認",
  delete: "刪除",
  deleteCustomPrompt: "刪除自訂句子",
  deleteCustomPromptBody: (title) =>
    `這會從本機移除「${title}」，也會從最近使用與收藏移除。`,
  editCustomPrompt: "編輯句子",
  emptyCategoryCopy: "試試搜尋「聽不懂」、「計畫」或「不行」。",
  emptyCategoryTitle: "找不到符合的句子。",
  emptyCustomCopy: "按右上角「新增句子」，建立自己的常用提示。",
  emptyCustomTitle: "還沒有自訂句子。",
  emptyRecentCopy: "複製幾句後，最近使用會出現在這裡。",
  emptyRecentTitle: "還沒有最近使用。",
  favorite: "收藏",
  footerCategory: "←→ 分類",
  footerCopy: "Enter 複製",
  footerJump: "Home/End 跳轉",
  footerSearch: "/ 搜尋",
  footerSearchClose: "Esc 關閉搜尋",
  footerSelect: "↑↓ 選取",
  labelContent: "句子內容",
  labelTags: "標籤",
  labelTitle: "標題",
  language: "語言",
  myPromptsEyebrow: "My Prompts",
  newCustomPrompt: "新增句子",
  noticeAdded: (title) => `已新增：${title}`,
  noticeDeleted: (title) => `已刪除：${title}`,
  noticeUpdated: (title) => `已更新：${title}`,
  placeholderContent: "請先把這件事拆成 3 到 5 個步驟，並告訴我第一步要做什麼。",
  placeholderSearchSamples: "換個關鍵字，或試試搜尋「計畫」、「下一步」、「檢查」。",
  placeholderTags: "planning, codex, writing",
  placeholderTitle: "例如：請先拆任務",
  save: "儲存",
  searchAriaLabel: "搜尋救援句",
  searchPlaceholder: (packName, shortcut) => `搜尋 ${packName}...  / 或 ${shortcut}`,
  settings: "開啟偏好設定",
  unfavorite: "取消收藏"
};

const en: UiCopy = {
  addCustomPrompt: "Add prompt",
  allCategories: "All",
  cancel: "Cancel",
  categoryCustom: "My prompts",
  categoryRecent: "Recent",
  close: "Close",
  confirm: "Confirm",
  delete: "Delete",
  deleteCustomPrompt: "Delete custom prompt",
  deleteCustomPromptBody: (title) =>
    `This removes "${title}" from this device, recent prompts, and favorites.`,
  editCustomPrompt: "Edit prompt",
  emptyCategoryCopy: "Try searching for plan, next step, or check.",
  emptyCategoryTitle: "No matching prompts.",
  emptyCustomCopy: "Use Add prompt to create your own reusable prompt.",
  emptyCustomTitle: "No custom prompts yet.",
  emptyRecentCopy: "Copied prompts will show up here.",
  emptyRecentTitle: "No recent prompts yet.",
  favorite: "Favorite",
  footerCategory: "←→ Categories",
  footerCopy: "Enter Copy",
  footerJump: "Home/End Jump",
  footerSearch: "/ Search",
  footerSearchClose: "Esc Clear search",
  footerSelect: "↑↓ Select",
  labelContent: "Prompt text",
  labelTags: "Tags",
  labelTitle: "Title",
  language: "Language",
  myPromptsEyebrow: "My Prompts",
  newCustomPrompt: "Add prompt",
  noticeAdded: (title) => `Added: ${title}`,
  noticeDeleted: (title) => `Deleted: ${title}`,
  noticeUpdated: (title) => `Updated: ${title}`,
  placeholderContent: "Break this into 3 to 5 steps and tell me what to do first.",
  placeholderSearchSamples: "Try another keyword, or search for plan, next step, or check.",
  placeholderTags: "planning, codex, writing",
  placeholderTitle: "Example: Break this down",
  save: "Save",
  searchAriaLabel: "Search prompts",
  searchPlaceholder: (packName, shortcut) => `Search ${packName}...  / or ${shortcut}`,
  settings: "Open settings",
  unfavorite: "Remove favorite"
};

export function getUiCopy(locale: string): UiCopy {
  return locale === "en" ? en : zhTw;
}
