export type Category = {
  id: string;
  name: string;
};

export type RescuePrompt = {
  id: string;
  category: string;
  source?: "built-in" | "custom";
  title: string;
  text: string;
  tags: string[];
};

export type CustomPromptDraft = {
  category: string;
  title: string;
  text: string;
  tags: string;
};

export type ThemeMode = "system" | "light" | "dark";

export type UiCopy = {
  addCustomPrompt: string;
  appEyebrow: string;
  appTitle: string;
  cancel: string;
  categoryCustom: string;
  categoryFavorites: string;
  categoryRecent: string;
  categoryRecentEmpty: string;
  close: string;
  confirm: string;
  delete: string;
  deleteCustomPrompt: string;
  deleteCustomPromptBody: (title: string) => string;
  editCustomPrompt: string;
  favorite: string;
  emptyCategoryCopy: string;
  emptyCategoryTitle: string;
  emptyCustomCopy: string;
  emptyCustomTitle: string;
  emptyFavoritesCopy: string;
  emptyFavoritesTitle: string;
  emptyRecentCopy: string;
  emptyRecentTitle: string;
  footerCategory: string;
  footerCopy: string;
  footerFavorite: string;
  footerJump: string;
  footerSelect: string;
  labelContent: string;
  labelPlacement: string;
  labelTags: string;
  labelTitle: string;
  language: string;
  myPromptsEyebrow: string;
  newCustomPrompt: string;
  noticeAdded: (title: string) => string;
  noticeDeleted: (title: string) => string;
  noticeFavoriteAdded: (title: string) => string;
  noticeFavoriteRemoved: (title: string) => string;
  noticeUpdated: (title: string) => string;
  placeholderContent: string;
  placeholderTags: string;
  placeholderTitle: string;
  save: string;
  settings: string;
  settingsEyebrow: string;
  settingsAutostartChecking: string;
  settingsAutostartDescription: string;
  settingsAutostartTitle: string;
  settingsAutostartUnavailable: string;
  settingsClose: string;
  settingsGithubDescription: string;
  settingsGithubTitle: string;
  settingsNote: string;
  settingsShortcutDescription: (platformName: string) => string;
  settingsShortcutTitle: string;
  settingsThemeDark: string;
  settingsThemeDescription: string;
  settingsThemeLight: string;
  settingsThemeSystem: string;
  settingsThemeTitle: string;
  settingsTitle: string;
  settingsUpdateAvailable: (version: string, currentVersion: string) => string;
  settingsUpdateButtonCheck: string;
  settingsUpdateButtonInstall: string;
  settingsUpdateChecking: string;
  settingsUpdateDescription: string;
  settingsUpdateDownloading: string;
  settingsUpdateDownloadingPercent: (percent: number) => string;
  settingsUpdateError: string;
  settingsUpdateNotAvailable: string;
  settingsUpdateRestarting: string;
  settingsUpdateTitle: string;
  settingsWindowResetDescription: string;
  settingsWindowResetTitle: string;
  unfavorite: string;
};

export type PromptPack = {
  id: string;
  name: string;
  description: string;
  locale: string;
  version: string;
  author: string;
  categories: Category[];
  prompts: RescuePrompt[];
};
