export type Category = {
  id: string;
  name: string;
};

export type CustomCategory = Category & {
  createdAt: string;
  locale: string;
};

export type RescuePrompt = {
  id: string;
  category: string;
  locale?: string;
  source?: "built-in" | "custom";
  title: string;
  text: string;
  tags: string[];
};

export type CustomPromptDraft = {
  category: string;
  title: string;
  text: string;
  tags: string;
};

export type ThemeMode = "system" | "light" | "dark";

export type UpdateErrorCode = "checkFailed" | "installFailed";

export type UiCopy = {
  addCustomPrompt: string;
  appEyebrow: string;
  appTitle: string;
  cancel: string;
  categoryBuiltInGroup: string;
  categoryCreateOption: string;
  categoryCustom: string;
  categoryCustomGroup: string;
  categoryFavorites: string;
  categoryRecent: string;
  categoryRecentEmpty: string;
  tabConfused: string;
  tabExecute: string;
  tabImprove: string;
  tabResearchPlanning: string;
  tabReview: string;
  tabStart: string;
  tabConfusedHint: string;
  tabExecuteHint: string;
  tabImproveHint: string;
  tabResearchPlanningHint: string;
  tabReviewHint: string;
  tabStartHint: string;
  close: string;
  confirm: string;
  delete: string;
  deleteCustomCategory: string;
  deleteCustomCategoryBody: (title: string, promptCount: number) => string;
  deleteCustomPrompt: string;
  deleteCustomPromptBody: (title: string) => string;
  editCustomCategory: string;
  editCustomPrompt: string;
  customPromptBadge: string;
  favorite: string;
  emptyCategoryCopy: string;
  emptyCategoryTitle: string;
  emptyCustomCategoryCopy: string;
  emptyCustomCategoryTitle: string;
  emptyCustomCopy: string;
  emptyCustomTitle: string;
  errorCategoryDuplicate: string;
  errorCategoryRequired: string;
  emptyFavoritesCopy: string;
  emptyFavoritesTitle: string;
  emptyRecentCopy: string;
  emptyRecentTitle: string;
  footerCategory: string;
  footerCopy: string;
  footerFavorite: string;
  footerJump: string;
  footerSelect: string;
  labelCategoryName: string;
  labelContent: string;
  labelManageCategory: string;
  labelPlacement: string;
  labelTags: string;
  labelTitle: string;
  language: string;
  manageCustomCategories: string;
  manageCustomCategoriesDescription: string;
  myPromptsEyebrow: string;
  newCustomCategory: string;
  newCustomPrompt: string;
  onboardingDismiss: string;
  onboardingStepCopy: string;
  onboardingStepHotkey: (shortcutLabel: string) => string;
  onboardingStepPaste: string;
  onboardingTitle: string;
  noticeAdded: (title: string) => string;
  noticeCategoryAdded: (title: string) => string;
  noticeCategoryDeleted: (title: string) => string;
  noticeCategoryUpdated: (title: string) => string;
  noticeCopied: (title: string) => string;
  noticeCopyFailed: string;
  noticeDeleted: (title: string) => string;
  noticeFavoriteAdded: (title: string) => string;
  noticeFavoriteRemoved: (title: string) => string;
  noticeUpdated: (title: string) => string;
  noticeImported: (count: number) => string;
  noticeImportFailed: string;
  noticeExported: (count: number) => string;
  placeholderCategoryName: string;
  placeholderContent: string;
  placeholderTags: string;
  placeholderTitle: string;
  save: string;
  settings: string;
  settingsEyebrow: string;
  settingsAutostartChecking: string;
  settingsAutostartDescription: string;
  settingsAutostartTitle: string;
  settingsAutostartUnavailable: string;
  settingsClose: string;
  settingsGithubDescription: string;
  settingsGithubTitle: string;
  settingsImportButton: string;
  settingsExportButton: string;
  settingsPromptDataDescription: string;
  settingsPromptDataTitle: string;
  settingsNote: string;
  settingsShortcutDescription: (platformName: string) => string;
  settingsShortcutTitle: string;
  settingsThemeDark: string;
  settingsThemeDescription: string;
  settingsThemeLight: string;
  settingsThemeSystem: string;
  settingsThemeTitle: string;
  settingsTitle: string;
  settingsUpdateAvailable: (version: string, currentVersion: string) => string;
  settingsUpdateButtonCheck: string;
  settingsUpdateButtonInstall: string;
  settingsUpdateChecking: string;
  settingsUpdateCheckFailed: string;
  settingsUpdateDescription: string;
  settingsUpdateDownloading: string;
  settingsUpdateDownloadingPercent: (percent: number) => string;
  settingsUpdateError: string;
  settingsUpdateInstallFailed: string;
  settingsUpdateNotAvailable: string;
  settingsUpdateRestarting: string;
  settingsUpdateTitle: string;
  settingsWindowResetDescription: string;
  settingsWindowResetTitle: string;
  unfavorite: string;
};

export type PromptPack = {
  id: string;
  name: string;
  description: string;
  locale: string;
  version: string;
  author: string;
  categories: Category[];
  prompts: RescuePrompt[];
};
